Migrate to ROS2
sbgisen/system_monitor pull request #3
Opened 2024-10-09 09:02 UTC by Tacha-S

2024-10-10 01:50 UTC, jsupratman13 commented
これを使ってsoarのブランチはある？

2024-10-10 01:53 UTC, Tacha-S commented
一応用意しましたが、実機では見ていないです。
https://github.com/sbgisen/soar/tree/feature/system-monitor-ros2

> 後 custom message消しているけど、使わないから？

ros2としてはcustom messageだけのパッケージを作る必要があるが、使っていないし使う予定もないので消しました。

あと関係ないけどslackのDM見てほしいです。

2024-10-10 08:28 UTC, jsupratman13 commented
rosdep すると以下のerrorがでる
```
system_monitor: [hddtemp] defined as "not available" for OS version [*]
```

2024-10-10 08:36 UTC, Tacha-S commented
> hddtemp がまだUbuntu24.04用にrosdep解決されていなさそうです。
sudo apt install -y hddtempが必要。
hddtempのサービスが起動していないとportに接続できないなどでhdd monitorが落ちます。
サービスの起動やPC再起動等で対応してください

2024-10-10 08:52 UTC, Tacha-S commented
実機でも確認できました。

2024-10-17 11:44 UTC, jsupratman13 commented
> > hddtemp がまだUbuntu24.04用にrosdep解決されていなさそうです。
> > sudo apt install -y hddtempが必要。
> > hddtempのサービスが起動していないとportに接続できないなどでhdd monitorが落ちます。
> > サービスの起動やPC再起動等で対応してください

```
>> sudo apt install -y hddtemp
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package hddtemp is not available, but is referred to by another package. 
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'hddtemp' has no installation candidate
```

2024-10-18 00:14 UTC, Tacha-S commented
なんでないんだと思ったら、自分の環境azure_kinect入れるためにfocalのapt serverいれたままでした。一旦draftにします。

2024-10-18 07:38 UTC, Tacha-S commented
soar側もパラメータで無効化していたので、一時的にHDDの温度監視機能消しました。

2024-10-18 11:17 UTC, jsupratman13 requested changes
* __pycache__ いらない
* licenseごちゃごちゃになっているけど大丈夫？

2024-10-18 11:17 UTC, jsupratman13 commented on package.xml
> +  <!-- <buildtool_depend>ament_python</buildtool_depend> -->
buildtool_depend に入れない理由ありますか？どこの情報なの？

2024-10-18 11:17 UTC, jsupratman13 commented on system_monitor/ntp_monitor.py
> +                measured_offset = float(o.split(' ')[3]) * 1000000
確認していないけど、同じことをやっているてことかな？

2024-10-18 11:17 UTC, jsupratman13 commented on system_monitor/net_monitor.py
> +#!/usr/bin/env python
このファイルはリファクタリングしないの

2024-10-22 05:31 UTC, Tacha-S commented on package.xml
> +  <!-- <buildtool_depend>ament_python</buildtool_depend> -->
system_monitor: Cannot locate rosdep definition for [ament_python]

build_typeには指定できるけどrosdep解決できるものではないし、他のpythonパッケージでは明記していないので消します。

2024-10-22 05:32 UTC, Tacha-S commented on system_monitor/ntp_monitor.py
> +                measured_offset = float(o.split(' ')[3]) * 1000000
同じことをしています。(ubuntuの更新でコマンドのログが若干表記が変わったのでその対策)

2024-10-22 05:33 UTC, Tacha-S commented on system_monitor/net_monitor.py
> +#!/usr/bin/env python
どういうこと？

2024-10-22 06:07 UTC, Tacha-S commented
> __pycache__ いらない

これ自分も気になっているんだけど、何が原因で生成されるか知ってますか？

2024-10-22 06:12 UTC, Tacha-S commented on system_monitor/net_monitor.py
> +#!/usr/bin/env python
ああこれだけファイル移動になってないんですね。
https://github.com/sbgisen/system_monitor/pull/3/files#diff-254baea744e49647cd24aad3791d65decb58014309a4c6d93969d3500262f9b0
これがもとのファイルです。

2024-10-23 01:37 UTC, jsupratman13 commented on system_monitor/net_monitor.py
> +#!/usr/bin/env python
get_sys_net_stat と update_status_stale 関数は class NetMonitorに入れない感じ？（他のファイルだと 関数を全てクラス内に入っているから気になっただけ）

2024-10-23 01:38 UTC, jsupratman13 commented on package.xml
> +  <!-- <buildtool_depend>ament_python</buildtool_depend> -->
へー
そうなんだ

2024-10-23 01:41 UTC, jsupratman13 commented
> これ自分も気になっているんだけど、何が原因で生成されるか知ってますか？

node実行時に生成するのでは？

2024-10-23 02:02 UTC, Tacha-S commented on system_monitor/net_monitor.py
> +#!/usr/bin/env python
なるほど。
classに入れたかどうかは、nodeが必要かそうじゃないかの違いだと思いますが、
いれるようにしておきます。

2024-10-23 02:04 UTC, Tacha-S commented
> node実行時に生成するのでは？

それはそうなんだけど、
他のpython packageだと生成されないような気がするので、実行時に生成される、されないの違いってなんだろうということ。

2024-10-23 03:25 UTC, jsupratman13 commented
>  ignoreしてただけでした。

これついでに入れておく？

2024-10-23 03:32 UTC, Tacha-S commented
いれておきました。

2024-10-23 04:53 UTC, jsupratman13 approved these changes

2024-10-23 04:54 UTC, merged